name: fasq_serializer_generator
description: Build runner generator for automatically registering serializers from TypedQueryKey declarations
version: 0.1.1+1
repository: https://github.com/ishafiul/fasq
issue_tracker: https://github.com/ishafiul/fasq/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^4.0.0
  source_gen: ^4.1.0
  analyzer: ^8.1.1
  path:
  fasq: ^0.3.7+1

dev_dependencies:
  dart_style: 
  test: 

